### PR TITLE
Primary amine

### PR DESCRIPTION
**Pull request by swansonk14**
I added a property indicating whether a primary amine is present or not based on the SMARTS string `[$([N;H2;X3][CX4]),$([N;H3;X4+][CX4])]`.

### CODE REVIEW

**Comment by bdrown** [comment]
This is a decent idea. I'd like to see some unit testing for the new `has_primary_amine` function. We want to make sure that the SMARTS string doesn't match against secondary amines, anilines, or imines. Can you write a unit test for `has_primary_amine`? Maybe include two examples of an amine-containing molecule, one with only secondary amines, one aniline, and one imine.

Also should consider if what other functional groups, if any, should be searched for. Could use a more general function that searches a given molecule for predefined functional group names.

**Comment by swansonk14** [comment]
Thanks for the feedback! Those are good ideas so I'll work on implementing them over the next few days.

**Comment by swansonk14** [comment]
@bdrown I took your advice and wrote some unit tests for the primary amine function. The tests are all passing, but since I'm not a chemist by training, please check the SMILES I wrote to make sure I accurately covered all the cases you were interested in.

I also rewrote the `has_primary_amine` function and renamed it `has_functional_group`, which takes as input both a molecule and a SMARTS string to search for. I then added a `FUNCTIONAL_GROUP_TO_SMARTS` dictionary which maps from functional group name to the SMARTS that represents that functional group. Right now it only has the primary amine functional group, but adding other functional groups is as simple as adding their SMARTS to that dictionary.

Please let me know if these changes look alright or if there's anything else you would suggest.

**Comment by swansonk14** [comment]
@bdrown thank you for the feedback!

I had forgotten about the hard coding of primary amine in those locations so thanks for catching that! I've made some changes so now everything should be based on the functional groups dictionary defined at the top of `calc_props.py`. Some of the tests are still hard coded to primary amine, but I think that might be somewhat necessary since we need to manually specify whether each test SMILES has each functional group.

I also added the additional test cases you suggested and everything seems to be passing.

**Pull request merged**
